# - name: 单机部署测试
#   hosts: host565
#   become: true 
#   vars_files: 
#     - vars/mysql_conf.yml
#   tasks:
#     - ansible.builtin.import_role:
#         name: lipanpan_hub.work.mysqlc



- name: 主节点配置
  hosts: host11
  become: true 
  vars_files: 
    - vars/mysql_replica.yml
  tasks:
    - ansible.builtin.include_role:
        name: lipanpan_hub.work.mysqlc

- name: 第一个从节点配置
  hosts: host12
  become: true 
  vars_files: 
    - vars/mysql_replica.yml
  tasks:
    - ansible.builtin.include_role:
        name: lipanpan_hub.work.mysqlc
      vars:
        mysql_replication_role: 'slave'
        mysql_server_id: "2"


- name: 第二个从节点配置
  hosts: host13
  become: true 
  vars_files: 
    - vars/mysql_replica.yml
  tasks:
    - ansible.builtin.include_role:
        name: lipanpan_hub.work.mysqlc
      vars:
        mysql_replication_role: 'slave'
        mysql_server_id: "3"

