---
all:
  hosts:
    host564:
      ansible_host: 192.168.56.4
    host565:
      ansible_host: 192.168.56.5
    host566:
      ansible_host: 192.168.56.6
  children:
    db_servers:
      hosts:
        host565: 
        host566:

